batchSizes = {50, 100};
numEpochs = {40, 80, 120};

rowNames = {};
trainErrs = [];
valErrs = [];
for i = 1:numel(batchSizes)
    for j = 1:numel(numEpochs)
        bs = batchSizes{i};
        ne = numEpochs{j};
        [net, info, expdir] = finetune_cnn('modelType', sprintf('batchSize-%d-numEpochs-%d', bs, ne),...
                                           'batchSize', bs,...
                                           'numEpochs', ne);
        %errors{j + (i-1)*numel(numEpochs)} = sprintf('batchSize %d numEpochs %d train_err %f val_err %f',...
                %bs, ne, mean([info.train.top1err]), mean([info.val.top1err]));
        rowNames{j+(i-1)*numel(numEpochs)} = sprintf('batchSize %d numEpochs %d', bs, ne);
        trainErrs = [trainErrs; mean([info.train.top1err])];
        valErrs = [valErrs; mean([info.val.top1err])];
    end
end
table(trainErrs, valErrs, 'RowNames', [rowNames])

% [net, info, expdir] = finetune_cnn('modelType', sprintf('batchSize-%d-numEpochs-%d-lrPrev-[0.05,0.5]-lrNew-[0.5,2]', batchSize, numEpochs),...
% 'batchSize', batchSize,...
% 'numEpochs', numEpochs,...
% 'lr_prev_layers', [0.05,0.5],...
% 'lr_new_layers', [0.5,2]);
% 
% [net, info, expdir] = finetune_cnn('modelType', sprintf('batchSize-%d-numEpochs-%d-lrPrev-[0.05,0.5]-lrNew-[0.1,1]', batchSize, numEpochs),...
% 'batchSize', batchSize,...
% 'numEpochs', numEpochs,...
% 'lr_prev_layers', [0.05,0.5],...
% 'lr_new_layers', [0.1,1]);
% 
% [net, info, expdir] = finetune_cnn('modelType', sprintf('batchSize-%d-numEpochs-%d-freeze', batchSize, numEpochs),...
% 'batchSize', batchSize,...
% 'numEpochs', numEpochs,...
% 'lr_prev_layers', [0,0]);

% net, info, expdir] = finetune_cnn('modelType', sprintf('alexnet-batchSize-%d-numEpochs-%d-extraPreprocessing', batchSize, numEpochs),...
% 'batchSize', batchSize,...
% 'numEpochs', numEpochs, 'extraPreprocessing', true);